# config/cloudinary.yml
development:
  cloud_name: "dkixe8cv6"
  api_key: "532428964424841"
  api_secret: "ffL9r6SCRk-4zCZHhSRs5wmDiQ0"

production:
  cloud_name: "dkixe8cv6"
  api_key: "532428964424841"
  api_secret: "ffL9r6SCRk-4zCZHhSRs5wmDiQ0"