export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const SET_CATEGORY_SUCCESS = 'SET_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const EDITING_CATEGORY_SUCCESS = 'EDITING_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const SET_POST_SUCCESS = 'SET_POST_SUCCESS';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const EDITING_POST_SUCCESS = 'EDITING_POST_SUCCESS';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_STATUS_SUCCESS = 'EDIT_POST_STATUS_SUCCESS';

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const SET_COMMENT_SUCCESS = 'SET_COMMENT_SUCCESS';
export const GET_COMMENTSPOSTS_SUCCESS = 'GET_COMMENTSPOSTS_SUCCESS';
export const SET_COMMENTSPOST_SUCCESS = 'SET_COMMENTSPOST_SUCCESS';
